on:
  schedule:
    - cron: '1 * * * *'  

name: Main Workflow
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Every time
      run: echo "This step will always run"
