on:
  push:
    branches:
      - aparna
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'A review from octo-team was requested'
