name: build Workflow
on: push

jobs:
  maven-job:
    runs-on: ubuntu-latest
    steps:
      - name: create jar file
        run: |
             pwd
             ls
             echo "running mvn clean install"
             
