name: Build
on:
  push:
    branches:
      - aparna
    paths:
      - '**.sh'  
  schedule:
    - cron: "1 * * * *"  
   
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
         echo "No changes to commit"
