name: Build
on:
  schedule:
    - cron: "1 * * * *"  
   
jobs:
  build:
    name: Build
    if: github.event.schedule == "1 * * * *" 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
         echo "No changes to commit"
