name: build Workflow
on: workflow_dispatch

jobs:
  maven-job:
    runs-on: ubuntu-latest
    steps:
      - name: create jar file
        run: |
             echo "running mvn clean install"
             mvn clean install
