name: build Workflow
on: push

jobs:
  maven-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: list of files
        run: ls
  docker-job:
    runs-on: ubuntu-latest
    steps:
      - name: docker build
        run:  docker build -t hello-image:v1 .
      
             
