name: build Workflow
on: push

jobs:
  maven-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: list of files
        run: ls
      - name: Build and push
        run: mvn clean install
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: target-files
          path: target   
  docker-job:
    needs: maven-job
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: target-files
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
      
  
      
             
